version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=polska123
    networks:
        veggies_network:
          ipv4_address: 10.5.0.7
  server:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    # command: python manage.py migrate
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    networks:
      veggies_network:
        ipv4_address: 10.5.0.5
    depends_on:
      - db
  web:
    build: ./wegemania-web
    command: npm start
    volumes:
      - ./wegemania-web:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    networks:
      veggies_network:
        ipv4_address: 10.5.0.6
    depends_on:
      - server

networks:
  veggies_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

  
