version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=polska123
  server:
    build: ./src
    # command: ls
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db

